### ISSUE TITLE
I cannot make it to work

### ISSUE THREAD

**Issue by chicco0278** [anysniper/Frontend#1]
Code does not work. I have been trying to but it does not work.
What am I supposed to put on PARSE_DEFAULT_PASSWORD?
What is SOCKET_DAPP_ID?

issue I am facing is when trying to connect metamask, it just does not connect.
Inspecting Chrome network it shows access to PARSE is denied.

**Comment by anysniper** [comment]
PARSE_DEFAULT_PASSWORD is whatever you want to set. SOCKET_DAPP_ID, you can just use as it is now.

**Comment by chicco0278** [comment]
Build runs without issue until I try to connect with metamask, after signing the transaction Google Chrome shows an error which seems to be related to Parse returning an unauthorized error. Attached you can see it.
<img width="1156" alt="Schermata 2022-07-23 alle 00 09 58" src="https://user-images.githubusercontent.com/2557832/180575115-37bfd999-6d4a-4d00-a36b-78b7f0f29f80.png">
<img width="410" alt="Schermata 2022-07-23 alle 00 10 23" src="https://user-images.githubusercontent.com/2557832/180575125-f4552e6d-dbd3-4747-b4ba-c185fab9e46b.png">

**Comment by chicco0278** [comment]
Partially working now. Parse was the issue I guess.
