### ISSUE TITLE
Not a coder Help!

### ISSUE THREAD

**Issue by Cashforkrypto** [anysniper/Frontend#2]
A bit confused on creating the bot. Pictures would really help if possible.

The code from src/config.js is copied and pasted into Back4app? Where exactly is it pasted? In the Database section of Back4App?

**Comment by anysniper** [comment]
Create an app on Back4app. And then it will give you credentials that you can fill in config.js

You can get these credentials on Back4app's App Settings / Security & Keys

```
  PARSE_APP_ID: 'R0qwhAQIbNmHctk030RjGGlYD9hSTuytv...',
  PARSE_URL: 'https://parseapi.back4app.com',
  PARSE_MASTER_KEY: '',
  PARSE_JS_KEY: '1MT3Ew8i1yQUX4SIvqbDiaggfszvtZ....',  

```
