### ISSUE TITLE
Intercom is not defined

### ISSUE THREAD

**Issue by Mallinanga** [anysniper/Frontend#4]
All the help icons and info bubbles with explanations of various settings don't work cause "Intercom is not defined"

I suppose the team used Intercom to display those help texts, but now that this is open sourced, maybe it should be migrated to a plain old popup with the help tips?

**Comment by anysniper** [comment]
http://help.anysnipers.com/en/collections/3347092-quick-guide-to-anysniper

This is the link to each component
