### ISSUE TITLE
error when npm install

### ISSUE THREAD

**Issue by icekha757** [anysniper/Frontend#5]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

getting this error when entering npm installs, what am i doing wrong? thanks

**Comment by icekha757** [comment]
thanks for that it worked but the next step npm run serve is giving me this
Error: error:0308010C:digital envelope routines::unsupported

is there anything else i need to install or do ?thank you

**Comment by Mallinanga** [comment]
That's because your node version is 17+
Better to install LTS version which is ^16

Or else one other "solution" is to prepend your commands with export NODE_OPTIONS=--openssl-legacy-provider && npm run serve

**Comment by icekha757** [comment]
thank you!
